apiVersion: v1
kind: Service
metadata:
  name: cyclotron-svc
  namespace: cyclotron
spec:
  selector:
    app: cyclotron
    component: api
  type: ClusterIP
  ports:
  - name: http
    port: 8087
    targetPort: 8087