apiVersion: v1
kind: Service
metadata:
  name: cyclotron-site
  namespace: cyclotron
spec:
  selector:
    app: cyclotron
    component: ui
  type: ClusterIP
  ports:
  - name:  http
    port:  8088
    targetPort: 8088