version: '3'

services:
  mongodb:
    image: docker.io/amd64/mongo:4-bionic
    restart: always
    env_file:
      - config/mongo.env
    networks:
      - cyclotron
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
  cyclotron-svc:
    build: ../../cyclotron-svc/
    image: docker.io/fjudith/cyclotron-svc
    restart: always
    networks:
      - cyclotron
    ports:
      - 8077:8077
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017
  cyclotron-site:
    build: ../../cyclotron-site/
    image: docker.io/fjudith/cyclotron-site
    restart: always
    networks:
      - cyclotron
    ports:
      - 8087:8087
    depends_on:
      - cyclotron-svc
  

networks:
  cyclotron:
    driver: bridge

volumes:
  mongo-data:
  mongo-config: